kind: Callables
callables:
  - fn: ds_humanize
    ds: xref=ds
    annotate: Creates humanized ds
  - fn: ds_join
    dsl: xref=ds
    dsr: xref=ds
    dslkey: str#list
    dsrkey: str#list
    type: enum#left,right,strict,diff
  - fn: ds_concat
    ds: xref=ds
    concat: str=area-headline,due_date-end_date#list
  - fn: ds_render
    ds: xref=ds
    rag: str=due_date#list
  - fn: ds_vxform
    xlation: xref=ds
  - fn: ds_cxform
    xlation: xref=ds
